apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mockylab-fe-tls
  namespace: default
spec:
  secretName: mockylab-fe-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - app.mockylab.com    