apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockylab-fe-deployment
  namespace: default
  labels:
    app: mockylab-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockylab-fe
  template:
    metadata:
      labels:
        app: mockylab-fe
    spec:
      containers:
      - name: mockylab-fe
        image: ghcr.io/arenndev/mockylab-fe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.mockylab.com"
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: "400m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      imagePullSecrets:
      - name: ghcr-secret
      nodeSelector:
        kubernetes.io/arch: amd64
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 