apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mockylab-fe-monitor
  namespace: default
  labels:
    app: mockylab-fe
    release: prometheus  # Prometheus operatörünüzün seçicisiyle eşleşmeli
spec:
  selector:
    matchLabels:
      app: mockylab-fe  # Servisinizin etiketleriyle eşleşmeli
  endpoints:
  - port: http  # Servisinizdeki port adıyla eşleşmeli
    path: /api/metrics
    interval: 15s
    scrapeTimeout: 10s 