apiVersion: v1
kind: Service
metadata:
  name: mockylab-fe-service
  namespace: default
  labels:
    app: mockylab-fe
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: mockylab-fe 