name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            NODE_ENV=production
            NEXT_TELEMETRY_DISABLED=1

      - name: Setup kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Check cluster and deployment
        run: |
          echo "Checking cluster connection..."
          kubectl get nodes
          
          echo "Checking deployment in default namespace..."
          kubectl get deployment mockylab-fe-deployment

      - name: Update Deployment
        run: |
          kubectl rollout restart deployment/mockylab-fe-deployment
          kubectl rollout status deployment/mockylab-fe-deployment

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/mockylab-fe-deployment.yaml
          kubectl apply -f k8s/mockylab-fe-service.yaml
          kubectl apply -f k8s/fe-http-middleware.yaml
          kubectl apply -f k8s/mockylab-fe-ingress.yaml
          kubectl apply -f k8s/mockylab-fe-networkpolicy.yaml
          kubectl apply -f k8s/mockylab-fe-hpa.yaml 